language: node_js
node_js:
- 4.2
before_install:
- npm install -g grunt-cli
- npm install -g bower
- bower install
- npm update
- bower update
notifications:
  email:
    on_success: change
    on_failure: change
sudo: false
cache:
  directories:
  - node_modules
env:
  global:
    secure: "eu2bqSbtF/gfBed80KzeeVc/5k8HwQGSqIQN8x1Li6AKV53uMvDVZ9DFeVxqzVIOEoEPjIguLXwQUncSHxjvSV9kgb9sHQ+wDCjA1psX0fU4kEk//4SMfZeatLyivkhW6wwdVMVYkOK1qEvaPUwObscqfQYFwoKUHXh5R06o//s="
